generated: '2026-08-13'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.zoominfo.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct 21 16:25:54 2026 GMT
  hsts: null
- host: api.zoominfo.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct 21 16:25:54 2026 GMT
  hsts: null
domains:
- domain: zoominfo.com
  dnssec: false
  caa:
  - 0 issuewild "pki.goog; cansignhttpexchanges=yes"
  - 0 issuewild "ssl.com"
  - 0 iodef "mailto:security@zoominfo.com"
  - 0 issue "amazon.com"
  - 0 issue "comodoca.com"
  - 0 issue "digicert.com; cansignhttpexchanges=yes"
  spf: true
  dmarc: true
  dmarc_policy: reject
